In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
lr = LogisticRegression() #logisticregression
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

C:\Users\Sai Sushma Iska\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9518518518518518

In [5]:
svm =SVC() #svm
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9851851851851852

In [6]:
rf = RandomForestClassifier(n_estimators=40) #randomforest
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9592592592592593

In [7]:
from sklearn.model_selection import cross_val_score #cross_val_score

In [8]:
#logisticRegression model performance using cross_val_score
LR=cross_val_score(LogisticRegression(), digits.data, digits.target,cv=5)
LR

C:\Users\Sai Sushma Iska\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Sai Sushma Iska\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [9]:
svm = cross_val_score(SVC(), digits.data, digits.target,cv=5)
svm

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [10]:
RF = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=5)
RF

array([0.93055556, 0.89444444, 0.94428969, 0.95543175, 0.91922006])

In [11]:
np.average(LR)

0.9137650882079852

In [12]:
np.average(svm)

0.9632838130609718

In [13]:
np.average(RF)

0.9287883008356547